name: Github Packages deployment

on:
  # Publishes packages on release (the Rhino version should not be
  # changed to '-SNAPSHOT' before creating the release in Github).
  release:
    types: [published]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Publish to GitHub Packages
      run: >-
        ./gradlew publish
        -PmavenReleaseRepo="https://maven.pkg.github.com/mozilla/rhino"
        -PmavenSnapshotRepo="https://maven.pkg.github.com/mozilla/rhino"
        -PmavenUser=${{ github.actor }}
        -PmavenPassword=${{ secrets.GITHUB_TOKEN }}
